name: CI
# on describes the trigger for workflow after push and pull on main branch

on:
   push:
      branches: [ main ]
   pull_request:
      branches: [ main ]
# Allow you to run the workflow manually from actions tab
   workflow_dispatch:

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-release:
    runs-on: ubuntu-latest # type of runner the job will runon

    steps: # sequence of jobs that would be executed as a part of job
      - uses: actions/checkout@v3 # checkout your repository under $GITHUB_WORKSPACE, so you can access it
      - name: Run a one line script # run one lines
        run: echo Hello,World!

      - name: Run a multi line script
        run:  | # run multiple lines
          echo Add other actions to build
          echo test and deploy projects



          
