name: 020-manual-input-workflow
# on describes the trigger for workflow after push and pull on main branch

on:
# Allow you to run the workflow manually from actions tab
   workflow_dispatch:
     inputs: #input work with manual workflow dispatch only
       name:
         description: 'Person to greet'
         default: 'World'
         required: true

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    runs-on: ubuntu-latest # type of runner the job will runon

    steps: # sequence of jobs that would be executed as a part of job
      - name: Send greeting
        run: echo "Hello, ${{github.event.inputs.name}}"        
